### ISSUE TITLE
Folder sync (opt-in)

### ISSUE THREAD

**Issue by RangerMauve** [RangerMauve/hyper-gateway#1]
Call `POST /$/sync/path/to/sync "folder/on/fs/to/sync"`

**Comment by josephmturner** [comment]
I think this feature would be useful for [hyper.el](https://git.sr.ht/~breatheoutbreathein/hyper.el).

**Comment by RangerMauve** [comment]
I think it could pose a security risk to implement, so I'd prefer it if we leave folder sync to client libraries. 👀
