### ISSUE TITLE
`hyper-gateway --version` returns `unknown`

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-gateway#15]
I'd expect a version number.

**Comment by josephmturner** [comment]
According to the [docs](https://yargs.js.org/docs/#api-reference-versionoption-description-version), "If no arguments are passed to version (.version()), yargs will parse the package.json of your module and use its version value."

But it seems this is not working?

**Comment by RangerMauve** [comment]
This is in the prebuilt binary? Might be due to the package.json not being bundled correctly.

**Comment by RangerMauve** [comment]
Try v3.4.1? https://github.com/RangerMauve/hyper-gateway/releases

**Comment by josephmturner** [comment]
Mmm, I just tried `hyper-gateway --version` with the new release, and I still get `unknown`.
