### ISSUE TITLE
What happens when the gateway is interrupted in the middle of something?

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-gateway#21]
What happens if the gateway is sent SIGINT in the middle of downloading a file?

What about SIGINT while uploading?

What about SIGKILL or other signals while uploading/downloading?

I tried interrupting the gateway with SIGINT (interactively, `C-c`) while in the middle of a large upload, and upon restarting the gateway, it appeared that the write had failed atomically. (Good!)

Thank you!!!

**Comment by josephmturner** [comment]
SIGINT will safely stop the gateway without file corruption.

**Comment by RangerMauve** [comment]
We listen for SIGINT and gracefully close the hypercore instance and that will mean that any blocks that were already saved will be saved, and any in-flight requests will get flushed from memory and need to be made again after reloading. We don't persist "file download progress" to disk anywhere.
