### ISSUE TITLE
Batched `PUT` requests

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-gateway#4]
Can hyper-gateway handle batching multiple changed files at once? Like a `PUT` request with many files?

**Comment by RangerMauve** [comment]
Not sure. It might be possible using HTTP keep-alives and connection reuse to the server. I'm not sure if you'd get much performance benefits from it.

If you want to upload several files to a directory at once, you can do so by sending a `multipart/formdata` request with several files using the name `file` and wahtever filname.

**Comment by RangerMauve** [comment]
Does FormData work for your use case for now?

**Comment by josephmturner** [comment]
In principle, it should!

`plz.el` [doesn't yet support](https://github.com/alphapapa/plz.el/issues/22) `multipart/formdata` `POST` requests.

If I run into issues with this approach, I'll make a new issue. Thank you :)
