### ISSUE TITLE
Add docs on starting a systemd service

### ISSUE THREAD

**Issue by RangerMauve** [RangerMauve/hyper-gateway#7]
- [ ] Systemd user service
- [ ] Bash script for downloading the binary
- [ ] Bash script for installing the user service and examples of how to use it

**Comment by josephmturner** [comment]
> * Bash script for downloading the binary

Should this script include a check to see if an existing binary is out of date? Or is that out of scope?

**Comment by josephmturner** [comment]
Should the service file ensure that `hyper-gateway` exits gracefully before the computer shuts down?

**Comment by RangerMauve** [comment]
If possible, that would be ideal. I never bothered to do that in dat-store for example and it seems to have been working fine.

**Comment by RangerMauve** [comment]
Just gotta make sure not to write stuff to it during shutdown. :P

**Comment by RangerMauve** [comment]
This is closed by #13
