### ISSUE TITLE
Include `hyper-gateway` version number in responses

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-gateway#9]
This would allow us to ensure that we're using the latest version.

**Comment by RangerMauve** [comment]
Yeah, it'd be cool to return a JSON file on a `GET` to `/`. Maybe it could also give the info about the hypercore-fetch and hyper-sdk versions.

**Comment by josephmturner** [comment]
> Yeah, it'd be cool to return a JSON file on a `GET` to `/`.

With a special `GET` request header, right? The behavior of `GET` on `/` is already defined: JSON array of top-level contents.

Alternatively, would it be too much overhead to send `X-HYPER-GATEWAY-VERSION` and `X-HYPERCORE-FETCH-VERSION` headers with every response?

**Comment by RangerMauve** [comment]
GET on `/` isn't the JSON array of files. That's a GET on `/hyper/key/`

So we should be able to put whatever we want in there.

**Comment by josephmturner** [comment]
My mistake. Okay - this sounds good to me!

**Comment by josephmturner** [comment]
Also, it appears that `hyper-gateway --version` returns "unknown". If you like, I can make a separate issue about this!

**Comment by RangerMauve** [comment]
Added in 3.3.0

**Comment by RangerMauve** [comment]
Try accessing http://localhost:4973/

**Comment by josephmturner** [comment]
Works great! We added a function in `hyperdrive.el` which uses this.
